Repository apolloconfig/apollo-java, pull requests merged in 2024-01, with the labels that each got.

#51 bump version to 2.3.0-SNAPSHOT
  CHANGES.md
  changes/changes-2.2.0.md
  pom.xml
Labels: size:S

#50 ProviderManager初始化动作不再在构造方法中实现
  CHANGES.md
  apollo-core/src/main/java/com/ctrip/framework/foundation/Foundation.java
  apollo-core/src/main/java/com/ctrip/framework/foundation/internals/DefaultProviderManager.java
  apollo-core/src/main/java/com/ctrip/framework/foundation/spi/ProviderManager.java
Labels: size:S, lgtm

#53 Implement parsing time based on pattern for @ApolloJsonValue
  CHANGES.md
  apollo-client/src/main/java/com/ctrip/framework/apollo/spring/annotation/ApolloAnnotationProcessor.java
  apollo-client/src/main/java/com/ctrip/framework/apollo/spring/annotation/ApolloJsonValue.java
  apollo-client/src/main/java/com/ctrip/framework/apollo/spring/property/AutoUpdateConfigChangeListener.java
  apollo-client/src/test/java/com/ctrip/framework/apollo/spring/JavaConfigPlaceholderAutoUpdateTest.java
  apollo-client/src/test/java/com/ctrip/framework/apollo/spring/JavaConfigPlaceholderTest.java
Labels: size:L, lgtm
